# -*- coding: utf-8 -*-
"""Multiple Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lwx9HQxrD4WC-rQ3CqrLQvXCnKvwmK8I

##Multiple Linear Regression
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

#veri setini import ediyoruz
data = pd.read_csv("multilinearregression.csv", sep=";")
data

reg = linear_model.LinearRegression()
reg.fit(data[['alan','odasayisi','binayasi']].values,data['fiyat'])

#230 m2, 4 odalı, 10 yaşında evin maaş tahmini
reg.predict([[230,4,10]])

#230 m2, 6 odalı, 10 yaşında evin maaş tahmini
reg.predict([[230,6,10]])

#230 m2, 6 odalı, 0 yaşında evin maaş tahmini
reg.predict([[230,6,0]])

reg.predict([[230,4,10],[230,6,10],[230,4,0]])

# multiple linear regression formülü
# y = a +b1x1+ b2x2+...
a = reg.intercept_
b1 = reg.coef_[0]
b2 = reg.coef_[1]
b3 = reg.coef_[2]

x1 = 230
x2 = 4
x3 = 0

y= a + b1*x1 + b2*x2 + b3*x3
y

"""##Model Kaydetme"""

import pickle
model_file = "evfiyattahmini.pickle"
pickle.dump(reg, open(model_file,'wb'))

"""##Model İmport"""

my_model = pickle.load(open("evfiyattahmini.pickle",'rb'))

my_model.predict([[230,6,0]])

